### ISSUE TITLE
Hi, is this project dead?

### ISSUE THREAD

**Issue by Joe23232** [rahul-thakoor/rust_gpiozero#30]
Hi, is this project dead?

**Comment by rahul-thakoor** [comment]
Looking for maintainers and contributors, see #11

**Comment by Joe23232** [comment]
@rahul-thakoor I wish I can be a developer myself. Oh well.

**Comment by dcroote** [comment]
The project is not dead :-)

**Comment by Raj2032** [comment]
@dcroote In my opinion in the near future there should be a "write once run everywhere" where it works on other miniboards such as the Odroid etc :)

**Comment by dcroote** [comment]
Hi @Raj2032 - I'm not familiar with those boards specifically, but for compiling a single source against an arbitrary target I'd highly recommend [cross](https://github.com/cross-rs/cross). I used it recently to cross-compile this crate for the Raspberry Pi Zero W.

**Comment by Raj2032** [comment]
@dcroote I see thanks mate

**Comment by rahul-thakoor** [comment]
I think @Raj2032 is looking for a generic hardware abstraction layer for other mcus?

perhaps checkout out https://github.com/rust-embedded/awesome-embedded-rust
